#!/bin/sh
### BEGIN INIT INFO
# Provides:          aria2c
# Required-Start:    $network $local_fs $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable aria2c by daemon.
### END INIT INFO
DAEMON=/usr/bin/aria2c
CONFPATH=/etc/Aria2c/aria2c.conf

case "$1" in
start)
sleep 1
iptables -A INPUT -p tcp --dport 6800 -j ACCEPT
iptables -A INPUT -p tcp --dport 6881:6999 -j ACCEPT
iptables -A INPUT -p udp --dport 6881:6999 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 6800 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 6881:6999 -j ACCEPT
iptables -A OUTPUT -p udp --dport 6881:6999 -j ACCEPT
sleep 1
$DAEMON --conf-path=$CONFPATH -D
;;
stop)
killall -9 aria2c
;;
restart)
killall -9 aria2c
sleep 3
$DAEMON --conf-path=$CONFPATH -D
;;
*)
echo "Usage: aria2c {start|stop|restart}"
exit 1
esac
exit 0